import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { LungCarcinomaTable } from "src/features/lungCarcinoma/ui/LungCarcinomaTable";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography variant="h2" fontSize="3em" fontWeight="bold">
        Data Table
      </Typography>

      <LungCarcinomaTable />
    </div>
  );
};

export default Home;
