import { Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Layout } from "src/components/Layout/Layout";
import { LungCarcinomaTable } from "src/features/lungCarcinoma/ui/LungCarcinomaTable";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Lung Carcinoma Associated Targets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout pageTitle="Lung Carcinoma Associated Targets">
        <LungCarcinomaTable />
      </Layout>
    </div>
  );
};

export default Home;
